const MathSidebar = [
    'concepts/math/introduction',
    {
      type: 'category',
      label: 'Linear Algebra',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/math/linearalgebra'
        }
      ]
    },
    {
      type: 'category',
      label: 'Statistics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/math/statistics'
        }
      ]
    },
    {
      type: 'category',
      label: 'Information Theory',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/math/information'
        }
      ]
    }, 
    {
      type: 'category',
      label: 'Calculus',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/math/calculus'
        }
      ]
    },
]


const MLConceptSidebar = [
    'concepts/mlconcept/introduction',
    {
      type: 'category',
      label: 'Data',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/mlconcept/data'
        }
      ]
    },
    {
      type: 'category',
      label: 'Evaluation & Sampling',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/mlconcept/evaluationNsampling'
        }
      ]
    },
    {
      type: 'category',
      label: 'Taxonomy',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/mlconcept/taxonomy'
        }
      ]
    },
    {
      type: 'category',
      label: 'Metrics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/mlconcept/metrics',
        }
      ]
    },
    {
      type: 'category',
      label: 'Regularization',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/mlconcept/regularization',
        }
      ]
    },
    'concepts/mlconcept/catastrophic_forgetting',
]


const DeepLearningSidebar = [
    'concepts/deeplearning/introduction',
    {
      type: 'category',
      label: 'Taxonomy',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/deeplearning/taxonomy'
        }
      ]
    },
    {
      type: 'category',
      label: 'Loss',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts/deeplearning/loss'
        }
      ]
    }
]


const LargeModelConceptSidebar = [
  'concepts/largemodel/introduction',
  'concepts/largemodel/scaling',
  'concepts/largemodel/decoding',
  'concepts/largemodel/temperature',
  'concepts/largemodel/hallucination',
  {
    type: 'category',
    label: 'Prompt Engineering',
    items: [
      {
        type: 'autogenerated',
        dirName: 'concepts/largemodel/prompt'
      }
    ]
  },
  {
    type: 'category',
    label: 'Tuning',
    items: [
      {
        type: 'autogenerated',
        dirName: 'concepts/largemodel/tuning'
      }
    ]
  }, 
]

const AgenticAISidebar = [
  {
    type: 'autogenerated',
    dirName: 'concepts/agenticAI'
  }
]

const ProgrammingSidebar = [
    {
      type: 'autogenerated',
      dirName: 'concepts/programming'
    }
]

const TorchSidebar = [
  {
    type: 'autogenerated',
    dirName: 'concepts/torch'
  }
]

const ConceptSidebars  = {
    MathSidebar: MathSidebar,
    TorchSidebar: TorchSidebar,
    MLConceptSidebar: MLConceptSidebar,
    DeepLearningSidebar: DeepLearningSidebar,
    LargeModelConceptSidebar: LargeModelConceptSidebar,
    AgenticAISidebar: AgenticAISidebar,
    ProgrammingSidebar: ProgrammingSidebar,
}


export default ConceptSidebars;