const DataSidebars = {
    DataImageSidebar: [
      {
        type: 'autogenerated',
        dirName: 'data/image',
      }
    ],
    DataTextSidebar: [
      {
        type: 'autogenerated',
        dirName: 'data/text',
      }
    ],
}


export default DataSidebars;