const MLModelSidebar  = [
    {
      type: 'autogenerated',
      dirName: 'models/mlmodel',
    },
]


const AIModelSidebar = [
    'models/aimodel/intro',
    {
        type: 'category',
        label: 'Transformer',
        items: [
          {
            type: 'autogenerated',
            dirName: 'models/aimodel/Transformer'
          }
        ]
    },
    {
        type: 'category',
        label: 'CLIP',
        items: [
          {
            type: 'autogenerated',
            dirName: 'models/aimodel/CLIP'
          }
        ]
    },
]


const LargeModelSidebar = [
    {
      type: 'autogenerated',
      dirName: 'models/largemodel',
    },
]
    

const ModelsSidebars = {
    MLModelSidebar: MLModelSidebar,
    AIModelSidebar: AIModelSidebar,
    LargeModelSidebar: LargeModelSidebar,
}


export default ModelsSidebars;