const Y2025Sidebar = [
    {
      type: 'category',
      label: 'Y2025',
      items: [
        {
          type: 'autogenerated',
          dirName: 'papers/y2025'
        }
      ]
    }
]

const BigtechSidebar = [
    {
      type: 'category',
      label: 'BigTech',
      items: [
        {
          type: 'autogenerated',
          dirName: 'papers/bigtech'
        }
      ]
    }
]

const PapersSidebars  = {
    Y2025Sidebar : Y2025Sidebar,
    BigtechSidebar: BigtechSidebar,
}




export default PapersSidebars