const PracticeSidebars = {
    TorchSidebar: [
      {
        type: 'autogenerated',
        dirName: 'practice/torch'
      }
    ],
    MOESideBar: [
      {
        type: 'autogenerated',
        dirName: 'practice/moe'
      }
    ],
    EfficienttrainSidebar: [
      {
        type: 'autogenerated',
        dirName: 'practice/efficienttrain'
      }
    ],
    MLOPsSidebar: [
      {
          type: 'autogenerated',
          dirName: 'practice/mlops'
      }
    ],
}


export default PracticeSidebars