/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import ModelsSidebars from './model_sidebars.js';
import DataSidebars from './data_sidebars.js';
import ConceptSidebars from './concept_sidebars.js';
import TaskSidebars from './task_sidebars.js';
import PapersSidebars from './papers_sidebars.js';

const CommunitySidebars = {
  CommunitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community'
    }
  ],
};

const sidebars = {
  ...ConceptSidebars,
  ...DataSidebars,
  ...ModelsSidebars,
  ...TaskSidebars,
  ...CommunitySidebars,
  ...PapersSidebars,
}

module.exports = sidebars;
