/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  CommunitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community'
    }
  ],
  MLConceptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'concepts/mlconcept'
    }
  ],
  MathSidebar: [
    'concepts/math/introduction',
    {
      type: 'autogenerated',
      dirName: 'concepts/math/linearalgebra',
    },
    {
      type: 'autogenerated',
      dirName: 'concepts/math/statistics'
    },
    {
      type: 'autogenerated',
      dirName: 'concepts/math/information'
    },
    {
      type: 'autogenerated',
      dirName: 'concepts/math/calculus'
    },
  ],
  ProgrammingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'concepts/programming',
    },
  ],
  DataImageSidebar: [
    {
      type: 'autogenerated',
      dirName: 'data/image',
    }
  ],
  DataTextSidebar: [
    {
      type: 'autogenerated',
      dirName: 'data/text',
    }
  ],
  MLModelSidebar: [
    {
      type: 'autogenerated',
      dirName: 'models/mlmodel'
    }
  ],
  AIModelSidebar: [
    {
      type: 'autogenerated',
      dirName: 'models/aimodel'
    }
  ],
  LargeModelSidebar: [
    {
      type: 'autogenerated',
      dirName: 'models/largemodel',
    },
  ],
  TorchSidebar: [
    {
      type: 'autogenerated',
      dirName: 'practice/torch'
    }
  ],
  EfficienttrainSidebar: [
    {
      type: 'autogenerated',
      dirName: 'practice/efficienttrain'
    }
  ],
  MLOPsSidebar: [
    {
        type: 'autogenerated',
        dirName: 'practice/mlops'
    }
  ],
};

module.exports = sidebars;
