
const RecommendationSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/recommendation'
  }
]

const InformationextractionSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/informationextraction'
  }
]

const RetrievalSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/retrieval'
  }
]

const KnowledgegraphSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/knowledgegraph'
  }
]

const LLMSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/llm&prompt'
  }
]

const EtcSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/etc'
  }
]

const EfficienttrainSidebar = [
  {
    type: 'autogenerated',
    dirName: 'tasks/efficienttrain'
  }
]

const MlopsSidebar = [
  {
      type: 'autogenerated',
      dirName: 'tasks/mlops'
  }
]

const TaskSidebars  = {
    RecommendationSidebar: RecommendationSidebar,
    InformationextractionSidebar: InformationextractionSidebar,
    RetrievalSidebar: RetrievalSidebar,
    KnowledgegraphSidebar: KnowledgegraphSidebar,
    LLMSidebar: LLMSidebar,
    EfficienttrainSidebar: EfficienttrainSidebar,
    MlopsSidebar: MlopsSidebar,
    EtcSidebar: EtcSidebar
}

export default TaskSidebars;