const TaskSidebars = {
    RecommendationSidebar: [
      {
        type: 'autogenerated',
        dirName: 'tasks/recommendation'
      }
    ],
    InformationextractionSidebar: [
      {
        type: 'autogenerated',
        dirName: 'tasks/informationextraction'
      }
    ],
    RetrievalSidebar: [
      {
        type: 'autogenerated',
        dirName: 'tasks/retrieval'
      }
    ],
    KnowledgegraphSidebar: [
      {
        type: 'autogenerated',
        dirName: 'tasks/knowledgegraph'
      }
    ],
    LLMSidebar: [
      {
        type: 'autogenerated',
        dirName: 'tasks/llm&prompt'
      }
    ],
}


export default TaskSidebars